#!python3
import tkinter as tk
from tkinter import *

main = tk.Tk()
main.title("T-Town Veterinary Clinic Database")
main.geometry("500x200")
main.resizable(0, 0)


dogphoto = PhotoImage(file = "dog.png")
label1 = tk.Label(main, image = dogphoto,)
label2 = tk.Label(main, text = "Client Database", font = ("Comic Sans MS", 11))
searchF = tk.Frame(main)
searchBox = tk.Entry(master = searchF, width = 20)
search = tk.Button(master = searchF, text = "Search by Name", font = ("Comic Sans MS", 11))
frame1 = tk.Frame(main)
name = tk.Label(master = frame1, text = "Name", font = ("Comic Sans MS", 11))
nameB = tk.Entry(master = frame1, width = 15)
typE = tk.Label(master = frame1, text = "Type", font = ("Comic Sans MS", 11))
typEB = tk.Entry(master = frame1, width = 15)
breed = tk.Label(master = frame1, text = "Breed", font = ("Comic Sans MS", 11))
breedB = tk.Entry(master = frame1, width = 15)
owner = tk.Label(master = frame1, text = "Owner", font = ("Comic Sans MS", 11))
ownerB = tk.Entry(master = frame1, width = 15)
birth = tk.Label(master = frame1, text = "Birthdate", font = ("Comic Sans MS", 11))
birthB = tk.Entry(master = frame1, width = 15)
frame2 = tk.Frame(main)
previous = tk.Button(main, text = "< Previous", font = ("Comic Sans MS", 11))
save = tk.Button(main, text = "Save Entry", font = ("Comic Sans MS", 11))
nexT = tk.Button(main, text = "Next >", font = ("Comic Sans MS", 11))

label1.pack(side = TOP, anchor = NW)
label2.place(x = 200, y = 50)
searchF.place(x = 275, y = 0)
searchBox.pack(side = "right")
search.pack(side = "right")
frame1.pack()
name.grid(row = 0, column = 0)
nameB.grid(row = 1, column = 0)
typE.grid(row = 0, column = 1)
typEB.grid(row = 1, column = 1)
breed.grid(row = 0, column = 2)
breedB.grid(row = 1, column = 2)
owner.grid(row = 0, column = 3)
ownerB.grid(row = 1, column = 3)
birth.grid(row = 0, column = 4)
birthB.grid(row = 1, column = 4)
frame2.pack(side = BOTTOM)
previous.place(x = 0, y = 165)
save.place(x = 200, y = 165)
nexT.place(x = 440, y = 165)

main.mainloop()